<a href="https://colab.research.google.com/github/eldhosekroy/churn_prediction/blob/main/Churn_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Import Libraries**

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

#**Data Collection**

In [28]:
base_dir = os.getcwd()

input_dir = base_dir

enrolled_file = os.path.join(input_dir, 'Endrolled & registred.xlsx')
crm_file = os.path.join(input_dir, 'CRM-All contacts.xlsx')
notes_file = os.path.join(input_dir, 'All Notes-Contacts_copy.xlsx')

enrolled = pd.read_excel(enrolled_file)
crm = pd.read_excel(crm_file)
notes = pd.read_excel(notes_file)

##**Display datas**

In [29]:
enrolled.head()

,Contact Id,Contact Owner.id,Contact Owner,First Name,Last Name,Email Opt Out,college Name.id,college Name,Track Interested,Tag,...,Gender,Year of Graduation,Experience,Test,Followup Email,Invoice,Mode of Program Joined,Program Location,Region,Whatsapp Number
0,zcrm_560042000000440092,zcrm_560042000000283001,SalesPerson-2,NaN,AJSAL Mohammed T S,False,NaN,NaN,Python Full stack,NaN,...,Male,NaN,NaN,False,False,Yes,NaN,NaN,NaN,NaN
1,zcrm_560042000000466061,zcrm_560042000000283001,SalesPerson-2,NaN,Abhishek R J,False,NaN,NaN,Datascience,NaN,...,NaN,2022.0,NaN,False,False,NaN,NaN,NaN,NaN,NaN
2,zcrm_560042000000565094,zcrm_560042000000331113,SalesPerson-9,Alan,Thomas,False,NaN,NaN,NaN,NaN,...,Male,2023.0,NaN,False,False,Yes,NaN,NaN,NaN,NaN
3,zcrm_560042000000583691,zcrm_560042000000331113,SalesPerson-9,NaN,Abhinav,False,NaN,NaN,NaN,Ayisha,...,Male,2023.0,NaN,False,False,Yes,NaN,NaN,NaN,NaN
4,zcrm_560042000000604837,zcrm_560042000000283001,SalesPerson-2,NaN,Albin Shaji,False,NaN,NaN,NaN,Enrolled,...,NaN,2024.0,0.0,False,True,Yes,NaN,NaN,NaN,NaN

In [30]:
crm.head()

,Contact Owner.id,Contact Owner,First Name,Last Name,Email Opt Out,college Name.id,college Name,Track Interested,Description,Created Time,...,Course,Gender,Year of Graduation,Experience,Test,Followup Email,Invoice,Mode of Program Joined,Program Location,Region
0,zcrm_560042000000283001,SalesPerson-2,NaN,man,False,NaN,NaN,NaN,NaN,2023-12-07 16:29:44,...,NaN,NaN,2024.0,NaN,False,False,Yes,NaN,NaN,NaN
1,zcrm_560042000000283001,SalesPerson-2,NaN,mahima,False,NaN,NaN,Datascience,NaN,2023-12-07 17:02:32,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
2,zcrm_560042000000283001,SalesPerson-2,NaN,feeba,False,NaN,NaN,Datascience,NaN,2023-12-07 17:02:32,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
3,zcrm_560042000000283001,SalesPerson-2,NaN,devadath,False,NaN,NaN,Datascience,NaN,2023-12-07 17:02:32,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN
4,zcrm_560042000000283001,SalesPerson-2,NaN,keerthy,False,NaN,NaN,Datascience,NaN,2023-12-07 17:02:32,...,NaN,NaN,NaN,NaN,False,False,NaN,NaN,NaN,NaN

In [31]:
notes.head()

,Note Id,Note Owner.id,Note Owner,Note Title,Note Content,Parent ID.id,Parent ID,Created By.id,Created By,Modified By.id,Modified By,Created Time,Modified Time
0,zcrm_560042000001333918,zcrm_560042000001286184,SalesPerson-21,NaN,SIJINA\nANOTHER CALLING,zcrm_560042000000424058,sijina,zcrm_560042000001286184,Udhya P U,zcrm_560042000001286184,Udhya P U,2024-05-29 12:25:20,2024-05-29 12:25:20
1,zcrm_560042000001333864,zcrm_560042000001286184,SalesPerson-21,NaN,SONU\nDATA ANALYTICS ALREADY INTERNSHIP DONE,zcrm_560042000000424059,sonu,zcrm_560042000001286184,Udhya P U,zcrm_560042000001286184,Udhya P U,2024-05-29 12:10:28,2024-05-29 12:10:28
2,zcrm_560042000001333760,zcrm_560042000001286184,SalesPerson-21,NaN,JOINED WORK,zcrm_560042000000424064,jainpaul,zcrm_560042000001286184,Udhya P U,zcrm_560042000001286184,Udhya P U,2024-05-29 11:58:41,2024-05-29 11:58:41
3,zcrm_560042000001370043,zcrm_560042000001286184,SalesPerson-21,NaN,currently doing job,zcrm_560042000000424066,sanjeeth,zcrm_560042000001286184,Udhya P U,zcrm_560042000001286184,Udhya P U,2024-05-29 14:35:33,2024-05-29 14:35:33
4,zcrm_560042000001333945,zcrm_560042000001286184,SalesPerson-21,NaN,SHILKA\nNOT CONNECTED,zcrm_560042000000424074,shilka,zcrm_560042000001286184,Udhya P U,zcrm_560042000001286184,Udhya P U,2024-05-29 12:27:35,2024-05-29 12:27:35

#**Data Exploration**

In [32]:
enrolled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274 entries, 0 to 1273
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Contact Id              1274 non-null   object
 1   Contact Owner.id        1274 non-null   object
 2   Contact Owner           1274 non-null   object
 3   First Name              152 non-null    object
 4   Last Name               1274 non-null   object
 5   Email Opt Out           1274 non-null   bool
 6   college Name.id         65 non-null     object
 7   college Name            65 non-null     object
 8   Track Interested        556 non-null    object
 9   Tag                     402 non-null    object
 10  Description             68 non-null     object
 11  Created By.id           1274 non-null   object
 12  Modified By.id          1274 non-null   object
 13  Created Time            1274 non-null   datetime64[ns]
 14  Modified Time           1274 non-null   datetime64[ns]
 15  Last Activity Time      1274 non-null   datetime64[ns]
 16  Unsubscribed Mode       0 non-null      float64
 17  Unsubscribed Time       0 non-null      float64
 18  Contact Name            1274 non-null   object
 19  City                    254 non-null    object
 20  Mailing State           9 non-null      object
 21  Mailing Zip             3 non-null      float64
 22  Mailing Country         8 non-null      object
 23  Program Joined.id       1035 non-null   object
 24  Program Joined          1035 non-null   object
 25  Source of lead          1109 non-null   object
 26  Pipeline owner.id       1011 non-null   object
 27  Semester                42 non-null     float64
 28  Batch Assigned to       237 non-null    object
 29  Lead Generated on       848 non-null    datetime64[ns]
 30  Course                  413 non-null    object
 31  Gender                  300 non-null    object
 32  Year of Graduation      319 non-null    float64
 33  Experience              14 non-null     float64
 34  Test                    1274 non-null   bool
 35  Followup Email          1274 non-null   bool
 36  Invoice                 1084 non-null   object
 37  Mode of Program Joined  440 non-null    object
 38  Program Location        438 non-null    object
 39  Region                  18 non-null     object
 40  Whatsapp Number         4 non-null      float64
dtypes: bool(3), datetime64[ns](4), float64(7), object(27)
memory usage: 382.1+ KB

In [33]:
enrolled.describe()

,Created Time,Modified Time,Last Activity Time,Unsubscribed Mode,Unsubscribed Time,Mailing Zip,Semester,Lead Generated on,Year of Graduation,Experience,Whatsapp Number
count,1274,1274,1274,0.0,0.0,3.000000,42.000000,848,319.000000,14.000000,4.000000e+00
mean,2025-03-02 01:55:06.603610624,2025-06-04 11:53:38.827315200,2025-06-15 06:58:25.073783296,NaN,NaN,679012.000000,5.023810,2024-11-02 04:43:35.094339584,2079.304075,0.071429,8.479450e+08
min,2023-12-07 16:29:44,2024-09-25 19:25:20,2024-09-25 19:25:20,NaN,NaN,673005.000000,2.000000,2003-06-10 00:00:00,2006.000000,0.000000,7.012189e+08
25%,2024-09-05 11:19:18,2025-01-22 12:24:57.500000,2025-01-22 14:49:26,NaN,NaN,677503.000000,4.000000,2024-06-23 00:00:00,2022.000000,0.000000,7.818011e+08
50%,2025-03-25 10:36:57.500000,2025-05-19 12:46:35,2025-05-19 12:50:00,NaN,NaN,682001.000000,6.000000,2024-11-04 12:00:00,2024.000000,0.000000,8.580451e+08
75%,2025-09-02 13:42:19.500000,2025-10-15 10:38:05,2025-10-15 10:38:06,NaN,NaN,682015.500000,6.000000,2025-07-01 00:00:00,2024.000000,0.000000,9.241890e+08
max,2026-02-23 11:44:53,2026-02-23 12:05:52,2026-02-24 17:14:04,NaN,NaN,682030.000000,8.000000,2026-02-23 00:00:00,20224.000000,1.000000,9.744707e+08
std,NaN,NaN,NaN,NaN,NaN,5202.234808,1.370207,NaN,1019.109883,0.267261,1.191900e+08

In [34]:
crm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46469 entries, 0 to 46468
Data columns (total 36 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Contact Owner.id        46469 non-null  object
 1   Contact Owner           46468 non-null  object
 2   First Name              857 non-null    object
 3   Last Name               46468 non-null  object
 4   Email Opt Out           46469 non-null  bool
 5   college Name.id         8360 non-null   object
 6   college Name            8360 non-null   object
 7   Track Interested        17914 non-null  object
 8   Description             8924 non-null   object
 9   Created Time            46469 non-null  datetime64[ns]
 10  Modified Time           46469 non-null  datetime64[ns]
 11  Last Activity Time      46162 non-null  datetime64[ns]
 12  Unsubscribed Mode       7 non-null      object
 13  Unsubscribed Time       7 non-null      datetime64[ns]
 14  Contact Name            46468 non-null  object
 15  Mailing City            3847 non-null   object
 16  City                    7446 non-null   object
 17  Mailing State           11 non-null     object
 18  Mailing Country         9 non-null      object
 19  Program Joined.id       1203 non-null   object
 20  Program Joined          1203 non-null   object
 21  Source of lead          40493 non-null  object
 22  Pipeline owner.id       35825 non-null  object
 23  Semester                4170 non-null   float64
 24  Batch Assigned to       6510 non-null   object
 25  Lead Generated on       36338 non-null  datetime64[ns]
 26  Course                  20463 non-null  object
 27  Gender                  4528 non-null   object
 28  Year of Graduation      6110 non-null   float64
 29  Experience              641 non-null    float64
 30  Test                    46469 non-null  bool
 31  Followup Email          46469 non-null  bool
 32  Invoice                 1328 non-null   object
 33  Mode of Program Joined  546 non-null    object
 34  Program Location        4744 non-null   object
 35  Region                  7123 non-null   object
dtypes: bool(3), datetime64[ns](5), float64(3), object(25)
memory usage: 11.8+ MB

In [35]:
crm.describe()

,Created Time,Modified Time,Last Activity Time,Unsubscribed Time,Semester,Lead Generated on,Year of Graduation,Experience
count,46469,46469,46162,7,4170.000000,36338,6110.000000,641.000000
mean,2025-01-06 03:13:00.833028352,2025-05-09 08:14:01.382900224,2025-07-25 05:35:44.607837696,2025-12-03 05:27:53.571428608,7.027818,2024-07-15 01:44:25.176949760,2026.763175,34.951638
min,2023-12-07 16:29:44,2024-05-22 17:40:02,2024-05-22 17:40:02,2025-11-27 15:57:28,0.000000,1998-02-08 00:00:00,2.000000,0.000000
25%,2024-04-17 15:14:56,2024-09-25 19:57:09,2024-12-09 17:07:15.500000,2025-11-30 04:25:24,4.000000,2024-02-04 00:00:00,2023.000000,0.000000
50%,2025-02-08 10:39:42,2025-05-19 12:47:01,2025-09-30 18:25:16,2025-12-04 21:35:19,5.000000,2024-09-06 00:00:00,2024.000000,0.000000
75%,2025-08-19 12:35:45,2025-09-30 18:26:06,2026-01-23 11:00:34,2025-12-05 14:18:27,6.000000,2025-06-05 00:00:00,2025.000000,0.000000
max,2026-02-13 12:14:42,2026-02-13 12:14:42,2026-02-13 12:20:22,2025-12-08 11:14:46,2022.000000,2087-12-14 00:00:00,20224.000000,2024.000000
std,NaN,NaN,NaN,NaN,62.470446,NaN,333.541364,262.757842

In [36]:
notes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13627 entries, 0 to 13626
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Note Id         13627 non-null  object
 1   Note Owner.id   13627 non-null  object
 2   Note Owner      13627 non-null  object
 3   Note Title      756 non-null    object
 4   Note Content    13598 non-null  object
 5   Parent ID.id    13627 non-null  object
 6   Parent ID       13626 non-null  object
 7   Created By.id   13627 non-null  object
 8   Created By      13627 non-null  object
 9   Modified By.id  13627 non-null  object
 10  Modified By     13627 non-null  object
 11  Created Time    13627 non-null  datetime64[ns]
 12  Modified Time   13627 non-null  datetime64[ns]
dtypes: datetime64[ns](2), object(11)
memory usage: 1.4+ MB

In [37]:
notes.describe()

                        Created Time                  Modified Time
count                          13627                          13627
mean   2025-07-01 22:25:00.722022400  2025-07-02 03:18:16.896382464
min              2023-12-13 16:49:00            2023-12-13 16:49:00
25%       2025-01-10 12:29:26.500000     2025-01-10 12:29:26.500000
50%              2025-11-14 10:13:34            2025-11-14 12:02:28
75%       2025-12-18 10:02:10.500000            2025-12-18 11:32:17
max              2026-02-13 12:18:48            2026-02-13 12:18:48

#**Data Pre-processing**

##**Data Cleaning**



*   Enrolled dataset

In [38]:
# checking null values for primary column
enrolled['Contact Id'].isnull().sum()

np.int64(0)

In [39]:
# checking duplicates values for primary column
enrolled['Contact Id'].duplicated().sum()

np.int64(0)

In [40]:
# checking duplicate values excluding contact_id column
enrolled.duplicated(subset=enrolled.columns.difference(['Contact Id'])).sum()

np.int64(0)

In [41]:
# Display the duplicate rows, considering all columns except 'Contact Id'
duplicate_rows = enrolled[enrolled.duplicated(subset=enrolled.columns.difference(['Contact Id']), keep=False)]
print(f"Number of duplicate rows (excluding 'Contact Id'): {len(duplicate_rows)}")
display(duplicate_rows.sort_values(by=list(enrolled.columns.difference(['Contact Id']))).head())

Number of duplicate rows (excluding 'Contact Id'): 0

Empty DataFrame
Columns: [Contact Id, Contact Owner.id, Contact Owner, First Name, Last Name, Email Opt Out, college Name.id, college Name, Track Interested, Tag, Description, Created By.id, Modified By.id, Created Time, Modified Time, Last Activity Time, Unsubscribed Mode, Unsubscribed Time, Contact Name, City, Mailing State, Mailing Zip, Mailing Country, Program Joined.id, Program Joined, Source of lead, Pipeline owner.id, Semester, Batch Assigned to, Lead Generated on, Course, Gender, Year of Graduation, Experience, Test, Followup Email, Invoice, Mode of Program Joined, Program Location, Region, Whatsapp Number]
Index: []

[0 rows x 41 columns]

In [42]:
# handling null values in different columns
# fill null values for 'invoice' column
enrolled['Invoice'] = enrolled['Invoice'].fillna('No')
enrolled['Invoice'] = enrolled['Invoice'].replace('yes', 'Yes')

# fill null values for 'program joined' column
enrolled['Program Joined'] = enrolled['Program Joined'].fillna('Not joined')

# fill null values for 'program location' column (mode)
mode_program_location = enrolled['Program Location'].mode()[0]
enrolled['Program Location'] = enrolled['Program Location'].fillna(mode_program_location)

# fill null values for 'experience' column
enrolled['Experience'] = enrolled['Experience'].fillna(0)

# fill null values for 'course' column
enrolled['Course'] = enrolled['Course'].fillna('Not mentioned')

# fill null values for 'lead generated on' column
# Sort the DataFrame by 'Lead Generated on' in ascending order
enrolled_sorted = enrolled.sort_values(by='Lead Generated on', ascending=True)
# Fill null values in 'Lead Generated on' with the previous valid date
enrolled['Lead Generated on'] = enrolled_sorted['Lead Generated on'].ffill()
# Sort back to original index order if needed (optional, often good practice)
enrolled = enrolled.sort_index()

#fill null values for 'batch assigned to' column
enrolled['Batch Assigned to'] = enrolled['Batch Assigned to'].fillna('Not assigned')

#fill null values for 'source of lead' column
mode_source_of_lead = enrolled['Source of lead'].mode()[0]
enrolled['Source of lead'] = enrolled['Source of lead'].fillna(mode_source_of_lead)

#fill null values for 'tag' column
enrolled['Tag'] = enrolled['Tag'].fillna('Not mentioned')

#fill null values for 'description' column
enrolled['Description'] = enrolled['Description'].fillna('Not mentioned')

#fill null values for 'mode of program joined' column
enrolled['Mode of Program Joined'] = enrolled['Mode of Program Joined'].fillna('Not mentioned')

In [43]:
print("Unique values and their counts in the 'Program joined' column:")
display(enrolled['Program Joined'].value_counts(dropna=False))

Unique values and their counts in the 'Program joined' column:

Program Joined
Not joined                        239
Jan DA 2026                        48
Aug DS 2025                        40
Aug DA 2025                        39
Nov DA 2025                        38
                                 ...
Oct One Month Programme 2025        1
Jan MERN 2026                       1
MERN Stack Jan25                    1
Nov One Month Programme 2025        1
Oct DA & DS Advanced programme      1
Name: count, Length: 85, dtype: int64

In [44]:
# Standardize the 'Program Joined' column
def standardize_program_joined_text(program_string):
    if pd.isna(program_string) or program_string == 'Not joined':
        return program_string

    program_string = str(program_string)

    # 1. Standardize month names (full to short form, and ensure proper case)
    month_mapping = {
        'January': 'Jan', 'February': 'Feb', 'March': 'Mar', 'April': 'Apr',
        'May': 'May', 'June': 'Jun', 'July': 'Jul', 'August': 'Aug',
        'September': 'Sep', 'October': 'Oct', 'November': 'Nov', 'December': 'Dec'
    }
    for full, short in month_mapping.items():
        program_string = re.sub(r'\b' + full + r'\b', short, program_string, flags=re.IGNORECASE)

    # Ensure month abbreviations are capitalized (e.g., "jan" -> "Jan")
    program_string = re.sub(r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b', lambda x: x.group(0).capitalize(), program_string, flags=0)

    # 2. Standardize common program keywords/abbreviations (case-insensitive search, consistent replacement)
    program_string = re.sub(r'\bprogramme\b', 'Program', program_string, flags=re.IGNORECASE)
    # Fix for 'Enrolleeee' issue: replace 'enroll' or 'enrollee' with 'Enrollee' (word boundary for accurate replacement)
    program_string = re.sub(r'\b(enroll|enrollee)\b', 'Enrollee', program_string, flags=re.IGNORECASE)

    # Specific course abbreviations - these should be uppercase
    program_string = re.sub(r'\bmern stack\b', 'MERN', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bmern\b', 'MERN', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata analytics\b', 'DA', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata analytic\b', 'DA', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata science\b', 'DS', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata sci\b', 'DS', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bfull stack\b', 'FS', program_string, flags=re.IGNORECASE)

    # Standardize 'One Month Program' variations
    program_string = re.sub(r'\b(One Month Programme|One Month Program)\b', 'One Month Program', program_string, flags=re.IGNORECASE)

    # Clean up extra spaces
    program_string = ' '.join(program_string.split())

    # Final capitalization for desired format (e.g., "DA May 2024"), then fix abbreviations
    program_string = program_string.title()
    program_string = program_string.replace('Da', 'DA').replace('Ds', 'DS').replace('Mern', 'MERN').replace('Fs', 'FS')
    # Ensure Enrollee keeps its capitalization
    program_string = program_string.replace('Enrollee', 'Enrollee')
    program_string = program_string.replace('One Month Program', 'One Month Program') # Keep as is after title()

    return program_string

# Apply this initial standardization to the 'Program Joined' column
enrolled['Program Joined'] = enrolled['Program Joined'].apply(standardize_program_joined_text)

In [45]:
print("Unique values and their counts in the 'Course' column:")
display(enrolled['Course'].value_counts(dropna=False))

Unique values and their counts in the 'Course' column:

Course
Not mentioned                                              861
BCA                                                         62
Btech-IT                                                    59
MCA                                                         58
BCom                                                        30
Btech-Non IT                                                25
MSc-IT                                                      24
BSc-IT                                                      20
Others                                                      16
MBA                                                         15
BSc-Non IT                                                  14
BVoc                                                        11
BA                                                          10
MSc-Non IT                                                   7
Mtech-IT                                                     5
B.Voc Data Analytics And Machine Learning                    4
graduated                                                    4
Diploma-IT                                                   4
MCom                                                         4
B.Tech/B.E.                                                  4
B.Sc                                                         3
Btech                                                        3
Diploma-Non IT                                               3
bsc_science                                                  2
b_tech                                                       2
B Tech                                                       1
Msc Big Data Analytics                                       1
Msc Computer Science(Data Analytics)                         1
MSc computer science (data analytics)                        1
BTech CSE                                                    1
B.A English literature                                       1
COMP                                                         1
BACHELOR of COMPUTER APPLICATION - COMPUTER APPLICATION      1
plus two                                                     1
B. Tech, Computer science and engineering                    1
b_com                                                        1
BTECH                                                        1
Post Graduation                                              1
2                                                            1
B.Tech                                                       1
BSC Computer Science                                         1
computer science engineering                                 1
diploma                                                      1
MCA (pursuing)                                               1
in_college                                                   1
Btech CS                                                     1
MA                                                           1
btech in EEE                                                 1
DEGREE BA                                                    1
Name: count, dtype: int64

In [46]:
# Function to standardize course names in the 'Course' column, focusing on preserving degree names
def standardize_course_name(course_string):
    if pd.isna(course_string) or str(course_string).strip().lower() == 'not mentioned':
        return 'NOT MENTIONED'

    course_string = str(course_string).upper()

    # Remove general noise: extra spaces, some punctuation, but be careful not to remove critical parts
    # Allow A-Z, 0-9, spaces, &, and hyphens. Only allow these characters
    course_string = re.sub(r'[^-A-Z0-9\s&]', '', course_string)
    course_string = ' '.join(course_string.split()) # Normalize spaces

    # Standardize common degree and course abbreviations
    course_string = course_string.replace('B.TECH', 'BTECH')
    course_string = course_string.replace('B.E.', 'BE')
    course_string = course_string.replace('M.TECH', 'MTECH')
    course_string = course_string.replace('BSC CS', 'BSC-CS')
    course_string = course_string.replace('MSC CS', 'MSC-CS')
    course_string = course_string.replace('COMPUTER APPLICATION', 'CA')
    course_string = course_string.replace('COMPUTER SCIENCE AND ENGINEERING', 'CSE')
    course_string = course_string.replace('COMPUTER SCIENCE', 'CS')
    course_string = course_string.replace('INFORMATION TECHNOLOGY', 'IT')
    course_string = course_string.replace('DATA ANALYTICS', 'DA')
    course_string = course_string.replace('DATA SCIENCE', 'DS')
    course_string = course_string.replace('BIG DATA ANALYTICS', 'BDA')
    course_string = course_string.replace('ENGLISH LITERATURE', 'ENG LIT')
    course_string = course_string.replace('PLUS TWO', 'PLUS TWO')
    course_string = course_string.replace('DIPLOMA', 'DIPLOMA')

    # Handle common course name variations before general IT/NON-IT replacement
    course_string = course_string.replace('B TECH', 'BTECH') # For 'B TECH'
    course_string = course_string.replace('B_TECH', 'BTECH') # For 'B_TECH'
    course_string = course_string.replace('B_COM', 'BCOM') # For 'B_COM'
    course_string = course_string.replace('CA CA', 'CA') # For 'CA - CA' and 'CA CA'

    # Specific fixes for previous output issues (e.g., missing hyphens)
    course_string = course_string.replace('BTECHIT', 'BTECH-IT')
    course_string = course_string.replace('MSCIT', 'MSC-IT')
    course_string = course_string.replace('BSCIT', 'BSC-IT')
    course_string = course_string.replace('MTECHIT', 'MTECH-IT')

    # Address remaining specific MSC-CS-DA variations directly after initial replacements
    course_string = course_string.replace('MSC-CS DA', 'MSC-CS-DA')
    course_string = course_string.replace('MSC-CSDA', 'MSC-CS-DA')

    # These replacements should happen after primary acronym standardization
    # This line might create issues for standalone 'IT' if not careful. For now, keep as is as other specific replacements handle degree-IT combinations.
    course_string = course_string.replace(' IT', '-IT') # Handle BTech IT etc. to BTech-IT
    course_string = course_string.replace('NON-IT', '-NON-IT') # Handle BTech-Non IT etc.

    # Normalize hyphens: replace multiple hyphens with single, remove spaces around hyphens
    course_string = re.sub(r'-+', '-', course_string).strip('-')
    course_string = re.sub(r'\s*-\s*', '-', course_string) # Remove spaces around hyphens
    course_string = ' '.join(course_string.split()) # Final space normalization after hyphen cleanup

    # Special handling for numerical and very short entries
    if course_string == '2':
        return 'PLUS TWO'
    if course_string == 'COMP':
        return 'CS'
    if course_string == 'POST GRADUATION':
        return 'PG'
    if course_string == 'BSC SCIENCE':
        return 'BSC'
    if course_string == 'GRADUATED':
        return 'GRADUATED'
    if course_string == 'IN COLLEGE' or course_string == 'IN_COLLEGE' or course_string == 'STUDENT': # Standardize IN_COLLEGE and convert 'STUDENT' if found as a course
        return 'UNSPECIFIED' # 'STUDENT' is a role, not a course
    if course_string == 'OTHERS':
        return 'OTHERS'

    # Remove words like 'PROGRAM', 'DEGREE', 'BACHELOR', 'MASTER' if they are standalone or don't contribute to specific degree names
    # This part should be less aggressive
    course_string = re.sub(r'\b(BACHELOR|MASTER|DEGREE|PROGRAMME|PROGRAM)\b', '', course_string).strip()
    course_string = re.sub(r'\b(OF|AND)\b', '', course_string).strip() # Remove common connectors

    course_string = ' '.join(course_string.split()) # Final space normalization

    # Map common variations to desired output, e.g., 'BTECH-IT' or 'BTECH'
    if 'BTECH' in course_string and 'NON' not in course_string and 'IT' not in course_string:
        course_string = 'BTECH'
    if 'BCA' in course_string:
        course_string = 'BCA'
    if 'MCA' in course_string:
        course_string = 'MCA'
    if 'BCOM' in course_string:
        course_string = 'BCOM'
    if 'MCOM' in course_string:
        course_string = 'MCOM'
    if 'BA' in course_string and 'DA' not in course_string:
        course_string = 'BA'
    if 'MA' in course_string:
        course_string = 'MA'
    if 'BSC' in course_string and 'NON' not in course_string and 'IT' not in course_string and 'CS' not in course_string:
        course_string = 'BSC'
    if 'MSC' in course_string and 'NON' not in course_string and 'IT' not in course_string and 'CS' not in course_string:
        course_string = 'MSC'
    if 'CSE' in course_string:
        course_string = 'BTECH-CSE'
    if 'CS' in course_string and 'BSC' not in course_string and 'MSC' not in course_string:
        course_string = 'CS'

    # Ensure consistency for entries like 'BTECH-IT', 'BSC-IT', etc.
    if course_string == 'BTECH-IT':
        pass # Keep as is
    elif course_string == 'BTECH-NON-IT':
        pass # Keep as is
    elif course_string == 'BSC-IT':
        pass
    elif course_string == 'MSC-IT':
        pass
    elif course_string == 'BSC-NON-IT':
        pass
    elif course_string == 'DIPLOMA-IT':
        pass
    elif course_string == 'DIPLOMA-NON-IT':
        pass
    elif course_string == 'MSC-CS-DA':
        pass

    # Final check for empty strings or remaining generic terms
    if not course_string or course_string == 'NAN' or course_string == 'UNKNOWN' or course_string == 'UNSPECIFIED':
        return 'UNSPECIFIED'

    return course_string

enrolled['Course'] = enrolled['Course'].apply(standardize_course_name)

#**Feature Engineering**

In [47]:
# Creating new columns for easier analysis

## Extract year, month and program name
def extract_year_and_course(program_string):
    if pd.isna(program_string) or program_string == 'Not joined':
        return None, 'Not joined', None # Added None for month

    program_string = str(program_string)

    # Extract year
    year_match = re.search(r'\b(202[0-9]|203[0-9]|204[0-9])\b', program_string)
    year = int(year_match.group(1)) if year_match else None

    # Extract month (3-letter abbreviation)
    month_match = re.search(r'\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b', program_string)
    month = month_match.group(1) if month_match else None

    cleaned_course_name = program_string
    # Remove year and month abbreviations
    cleaned_course_name = re.sub(r'\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b', '', cleaned_course_name, flags=0)
    cleaned_course_name = re.sub(r'\b(202[0-9]|203[0-9]|204[0-9])\b', '', cleaned_course_name)

    # Aggressively remove common extra words, standalone numbers, and specific unwanted patterns
    extra_words_to_remove = [
        'Program', 'Enrollee', 'One Month', 'Advanced', 'Training', 'Bootcamp', 'Course', 'Classes',
        'Online', 'Offline', 'Batch', 'Session', 'Beginner', 'Intermediate', 'Expert', 'Module'
    ]
    # Remove these words case-insensitively
    cleaned_course_name = re.sub(r'\b(' + '|'.join(extra_words_to_remove) + r')\b', '', cleaned_course_name, flags=re.IGNORECASE)

    # Remove any standalone numbers (e.g., 'DA 25' -> 'DA ') or numbers attached to words (e.g., 'DA25' -> 'DA')
    cleaned_course_name = re.sub(r'\s*\d+\s*', ' ', cleaned_course_name) # Remove standalone numbers
    cleaned_course_name = re.sub(r'\b([A-Z]+)(\d+)\b', r'\1', cleaned_course_name) # Remove trailing numbers like 'DA25'

    cleaned_course_name = re.sub(r' & ', '&', cleaned_course_name) # Standardize ampersand
    cleaned_course_name = cleaned_course_name.strip()
    cleaned_course_name = ' '.join(cleaned_course_name.split()) # Remove multiple spaces
    cleaned_course_name = cleaned_course_name.upper() # Convert to uppercase for final standardization

    final_course_name = 'UNSPECIFIED'

    # Define primary course names to recognize as prefixes, sorted by length (descending)
    primary_course_names = [
        'ROUNDED DS&GENAI PROFESSIONAL', 'GEN AI&PROMPT ENG', 'WEB DEV', 'MERN', 'FULL STACK',
        'DATA ANALYTICS', 'DATA SCIENCE', 'DS&ALGORITHMS', 'PYTHON', 'MLOPS', 'AI', 'BA', 'DM', 'ML',
        'DA', 'DS', 'FS', 'PEP', 'PY'
    ]
    primary_course_names.sort(key=len, reverse=True) # Ensure longer names are checked first

    found_primary = False
    for pc_name in primary_course_names:
        # Check if the cleaned course name starts with a primary course name, or is exactly it
        if cleaned_course_name.startswith(pc_name) or cleaned_course_name == pc_name:
            final_course_name = pc_name
            found_primary = True
            break

    # If no primary course name was found by prefix, but the cleaned_course_name is not empty, use it as is or apply specific mappings
    if not found_primary and cleaned_course_name != '':
        course_name_exact_mapping = {
            'DATA ANALYTICS': 'DA',
            'DATA SCIENCE': 'DS',
            'FULL STACK': 'FS',
            'MERN STACK': 'MERN',
            'ADVANCED': 'ADVANCED',
            'EE': 'ENROLLEE',
            'DA ENROLLEE': 'DA'
        }
        final_course_name = course_name_exact_mapping.get(cleaned_course_name, cleaned_course_name)

    # Ensure 'Churned' overrides any other logic if the original program_string was 'Churned'
    if program_string == 'Not joined':
        final_course_name = 'Not joined'
    elif final_course_name == '': # If it became empty after all processing, default to UNSPECIFIED
        final_course_name = 'UNSPECIFIED'

    return year, final_course_name, month # Updated return to include month

# Apply the year and course extraction on the newly standardized 'Program Joined Standardized' column
enrolled[['Program_Year', 'Program_Name', 'Program_Month']] = enrolled['Program Joined'].apply(lambda x: pd.Series(extract_year_and_course(x))) # Updated assignment
enrolled['Program_Month'] = enrolled['Program_Month'].fillna('NA')



## Create the 'role' column based on conditional logic
def assign_role(row):
    if row['Experience'] > 0:
        return 'Professional'
    elif row['Semester'] > 0:
        return 'Student'
    elif row['Year of Graduation'] > 0 and row['Experience'] == 0:
        # Assuming a current year for 'Idle or Career Gap' if no experience but graduated
        # For simplicity, we'll just check if they graduated and have no experience
        return 'Idle or Career Gap'
    return 'Unknown'

enrolled['role'] = enrolled.apply(assign_role, axis=1)



## Create the 'background' column based on course
def assign_background(course):
    if pd.isna(course) or course == 'NOT MENTIONED' or course == 'UNSPECIFIED':
        return 'UNKNOWN'

    # Define lists of common tech and non-tech courses
    tech_keywords = [
        'BTECH', 'BE', 'MTECH', 'BCA', 'MCA', 'BSC-CS', 'MSC-CS', 'CSE', 'CS', 'IT', 'DA', 'DS', 'BDA',
        'MSCIT', 'BSCIT', 'MTECHIT', 'MSC-CS-DA', 'BTECH-IT', 'BSC-IT', 'DIPLOMA-IT'
    ]

    non_tech_keywords = [
        'BCOM', 'MCOM', 'BA', 'MA', 'BSC', 'MSC', 'ENG LIT', 'PLUS TWO', 'DIPLOMA', 'PG',
        'BSC-NON-IT', 'DIPLOMA-NON-IT', 'GRADUATED', 'OTHERS'
    ]

    # Convert course to uppercase for case-insensitive matching
    course_upper = str(course).upper()

    for keyword in tech_keywords:
        if keyword in course_upper:
            return 'Tech'

    for keyword in non_tech_keywords:
        if keyword in course_upper:
            return 'Non-Tech'

    # If none of the above match, try to infer based on broader terms or default
    if 'TECH' in course_upper or 'SCIENCE' in course_upper or 'ENGINEERING' in course_upper:
        return 'Tech'
    elif 'ARTS' in course_upper or 'COMMERCE' in course_upper or 'HUMANITIES' in course_upper:
        return 'Non-Tech'

    return 'UNKNOWN'

enrolled['background'] = enrolled['Course'].apply(assign_background)

In [48]:
# fill null values of 'track interested' column
mode_track_interested = enrolled['Track Interested'].mode()[0]

enrolled.loc[
    enrolled['Track Interested'].isnull() & (enrolled['Program_Name'] != 'NOT JOINED'),
    'Track Interested'
] = enrolled['Program_Name']

# Fill any remaining null values in 'Track Interested' with the calculated mode
enrolled['Track Interested'] = enrolled['Track Interested'].fillna(mode_track_interested)

In [49]:
# Data type correction
float_columns = enrolled.select_dtypes(include=['float64']).columns

for col in float_columns:
    # Fill NaN values with 0 and then convert to integer
    enrolled[col] = enrolled[col].fillna(0).astype(int)

print("Data types after converting float columns to int:")
enrolled.info()

Data types after converting float columns to int:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274 entries, 0 to 1273
Data columns (total 46 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Contact Id              1274 non-null   object
 1   Contact Owner.id        1274 non-null   object
 2   Contact Owner           1274 non-null   object
 3   First Name              152 non-null    object
 4   Last Name               1274 non-null   object
 5   Email Opt Out           1274 non-null   bool
 6   college Name.id         65 non-null     object
 7   college Name            65 non-null     object
 8   Track Interested        1274 non-null   object
 9   Tag                     1274 non-null   object
 10  Description             1274 non-null   object
 11  Created By.id           1274 non-null   object
 12  Modified By.id          1274 non-null   object
 13  Created Time            1274 non-null   datetime64[ns]
 14  Modified Time           1274 non-null   datetime64[ns]
 15  Last Activity Time      1274 non-null   datetime64[ns]
 16  Unsubscribed Mode       1274 non-null   int64
 17  Unsubscribed Time       1274 non-null   int64
 18  Contact Name            1274 non-null   object
 19  City                    254 non-null    object
 20  Mailing State           9 non-null      object
 21  Mailing Zip             1274 non-null   int64
 22  Mailing Country         8 non-null      object
 23  Program Joined.id       1035 non-null   object
 24  Program Joined          1274 non-null   object
 25  Source of lead          1274 non-null   object
 26  Pipeline owner.id       1011 non-null   object
 27  Semester                1274 non-null   int64
 28  Batch Assigned to       1274 non-null   object
 29  Lead Generated on       1274 non-null   datetime64[ns]
 30  Course                  1274 non-null   object
 31  Gender                  300 non-null    object
 32  Year of Graduation      1274 non-null   int64
 33  Experience              1274 non-null   int64
 34  Test                    1274 non-null   bool
 35  Followup Email          1274 non-null   bool
 36  Invoice                 1274 non-null   object
 37  Mode of Program Joined  1274 non-null   object
 38  Program Location        1274 non-null   object
 39  Region                  18 non-null     object
 40  Whatsapp Number         1274 non-null   int64
 41  Program_Year            1274 non-null   int64
 42  Program_Name            1274 non-null   object
 43  Program_Month           1274 non-null   object
 44  role                    1274 non-null   object
 45  background              1274 non-null   object
dtypes: bool(3), datetime64[ns](4), int64(8), object(31)
memory usage: 431.8+ KB

In [50]:
# Displaying unique values for modified columns
columns_to_display = [
    'Track Interested', 'Program Joined', 'Source of lead', 'Batch Assigned to',
    'Course', 'Gender', 'Mode of Program Joined', 'Program_Year', 'Program_Month',
    'Program_Name', 'role', 'background'
]

for col in columns_to_display:
    print(f"\nUnique values for column '{col}':")
    display(enrolled[col].value_counts(dropna=False))

Unique values for column 'Track Interested':

Track Interested
DA                                     278
DS                                     247
Data Analytics                         211
Datascience                            189
Not joined                             152
MERN                                    34
Data Science                            29
Dataanalytics                           29
MERN Stack                              20
Data Analytics Intern                   13
Data Analyst                            10
Not Mentioned                            9
Python Full stack                        8
UNSPECIFIED                              6
Datascience/DataAnalytics                5
PEP                                      5
Data Analyst Intern                      4
Dataanalyst                              3
DataAnalytics                            3
Data Analytics Fresher                   2
Prompt Engineering                       2
Dataanlytics                             2
Microsoft AI Engineer                    2
Data analyst                             2
DataAnalyst                              2
GenAI & Prompt                           1
Data Science Intern                      1
GEN AI&PROMPT ENG                        1
Gen Ai & Prompt Engineering Intern       1
Datascience Internship for freshers      1
Gen Ai & Prompt Engineering              1
ROUNDED DS&GENAI PROFESSIONAL            1
Name: count, dtype: int64

Unique values for column 'Program Joined':

Program Joined
Not joined                      239
Jan DA 2026                      48
Aug DS 2025                      40
Aug DA 2025                      39
Nov DA 2025                      38
                               ...
Oct One Month Program 2025        1
Jan MERN 2026                     1
MERN Jan25                        1
Nov One Month Program 2025        1
Oct DA & DS Advanced Program      1
Name: count, Length: 85, dtype: int64

Unique values for column 'Source of lead':

Source of lead
Indeed                          420
Reference                       202
Digital Marketing (Goat add)    191
Infopark website                142
Enquiry                          78
Digital Marketing (Add On)       51
DM                               30
IV                               22
Workshop                         22
Seminar                          19
dm                               18
Website Enquiry                  16
infopark                         10
Naukri Paid                       8
Free internship campaign          7
Webinar                           5
Job Fair                          4
Social media                      4
Indeed Paid                       3
Carryover                         3
Infopark                          3
OLX                               3
Naukri Ad posting                 2
SEO                               2
Bulk Lead (3000)                  2
Infopark  website                 2
Dm                                1
free internship                   1
college referal                   1
Referals from Colleges            1
Linkedin                          1
Name: count, dtype: int64

Unique values for column 'Batch Assigned to':

Batch Assigned to
Not assigned           1037
2026-04-24 00:00:00      35
2026-06-24 00:00:00      32
2026-04-25 00:00:00      19
2026-02-25 00:00:00      18
2026-02-24 00:00:00      16
2026-10-24 00:00:00      16
2024-01-01 00:00:00      15
2026-01-25 00:00:00      12
2026-05-24 00:00:00      11
2026-03-25 00:00:00      11
2026-05-25 00:00:00      10
2026-11-24 00:00:00       8
2026-12-24 00:00:00       7
2026-03-24 00:00:00       5
2026-07-24 00:00:00       5
2026-09-24 00:00:00       4
2026-08-24 00:00:00       2
First Choice              2
2026-11-25 00:00:00       2
2026-10-25 00:00:00       2
2023-12-01 00:00:00       1
2026-08-25 00:00:00       1
2026-07-25 00:00:00       1
2026-02-26 00:00:00       1
2026-12-25 00:00:00       1
Name: count, dtype: int64

Unique values for column 'Course':

Course
NOT MENTIONED    861
BCA               62
BTECH-IT          59
MCA               59
BCOM              31
BA                27
BTECH-NON-IT      25
MSC-IT            24
BSC-IT            20
OTHERS            16
BTECH             16
BSC-NON-IT        14
MA                13
BVOC              11
MSC-NON-IT         7
MTECH-IT           5
GRADUATED          4
MCOM               4
BSC                3
BSCSCIENCE         2
PLUS TWO           2
CS                 2
MSC CSDA           1
MSC CS DA          1
MSC                1
CA-CA              1
PG                 1
BSC CS             1
INCOLLEGE          1
Name: count, dtype: int64

Unique values for column 'Gender':

Gender
NaN       974
Male      167
Female    131
M           2
Name: count, dtype: int64

Unique values for column 'Mode of Program Joined':

Mode of Program Joined
Not mentioned    834
Onsite           308
Online           130
online hybrid      1
Hybrid             1
Name: count, dtype: int64

Unique values for column 'Program_Year':

Program_Year
2025    522
0       355
2024    267
2026    130
Name: count, dtype: int64

Unique values for column 'Program_Month':

Program_Month
NA     255
Jan    133
Oct    114
Sep    103
Dec    103
Nov    101
Aug     90
Jun     84
Feb     76
Jul     66
May     64
Apr     64
Mar     21
Name: count, dtype: int64

Unique values for column 'Program_Name':

Program_Name
DA                               542
DS                               426
Not joined                       239
MERN                              52
UNSPECIFIED                        8
ROUNDED DS&GENAI PROFESSIONAL      3
PEP                                2
PY                                 1
GEN AI&PROMPT ENG                  1
Name: count, dtype: int64

Unique values for column 'role':

role
Unknown               937
Idle or Career Gap    295
Student                41
Professional            1
Name: count, dtype: int64

Unique values for column 'background':

background
UNKNOWN     874
Tech        298
Non-Tech    102
Name: count, dtype: int64

#### Operations to be done after visualization

In [10]:
# Removing irrelevant rows non active candidates
nonactive_candidates = enrolled[(enrolled['Invoice'] == 'No') & (enrolled['Program Joined'] == 'Not joined')].shape[0]
nonactive_candidates
enrolled = enrolled[~((enrolled['Invoice'] == 'No') & (enrolled['Program Joined'] == 'Not joined'))]

print(f"Shape of enrolled DataFrame after removing non-active candidates: {enrolled.shape}")

Shape of enrolled DataFrame after removing non-active candidates: (1139, 41)

In [11]:
# Removing irrelevant columns for churn prediction
columns_to_drop = [
    'First Name',
    'Last Name',
    'Email Opt Out',
    'college Name.id',
    'college Name',
    'Unsubscribed Mode',
    'Unsubscribed Time',
    'City',
    'Mailing State',
    'Mailing Zip',
    'Mailing Country',
    'Whatsapp Number',
    'Region'
]

enrolled = enrolled.drop(columns=columns_to_drop)

print(f"Shape of enrolled DataFrame after dropping columns: {enrolled.shape}")
display(enrolled.head())

Shape of enrolled DataFrame after dropping columns: (1139, 28)

,Contact Id,Contact Owner.id,Contact Owner,Track Interested,Tag,Description,Created By.id,Modified By.id,Created Time,Modified Time,...,Lead Generated on,Course,Gender,Year of Graduation,Experience,Test,Followup Email,Invoice,Mode of Program Joined,Program Location
0,zcrm_560042000000440092,zcrm_560042000000283001,SalesPerson-2,Python Full stack,NaN,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2023-12-19 11:01:38,2024-09-25 19:25:56,...,2023-12-19,Btech-Non IT,Male,0,0,False,False,Yes,NaN,NaN
1,zcrm_560042000000466061,zcrm_560042000000283001,SalesPerson-2,Datascience,NaN,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2023-12-26 15:20:10,2024-09-25 19:26:18,...,2023-12-26,BCom,NaN,2022,0,False,False,No,NaN,NaN
2,zcrm_560042000000565094,zcrm_560042000000331113,SalesPerson-9,NaN,NaN,NaN,zcrm_560042000000331113,zcrm_560042000000283001,2024-01-22 10:50:27,2024-09-25 19:28:00,...,2024-01-22,BCA,Male,2023,0,False,False,Yes,NaN,NaN
3,zcrm_560042000000583691,zcrm_560042000000331113,SalesPerson-9,NaN,Ayisha,NaN,zcrm_560042000000331113,zcrm_560042000000283001,2024-01-23 15:26:32,2025-05-19 12:49:04,...,2024-01-23,BCA,Male,2023,0,False,False,Yes,NaN,NaN
4,zcrm_560042000000604837,zcrm_560042000000283001,SalesPerson-2,NaN,Enrolled,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2024-01-28 22:15:36,2024-10-02 12:37:59,...,2024-01-18,MSc computer science (data analytics),NaN,2024,0,False,True,Yes,NaN,NaN

#**Data Cleaning**

*   Notes dataset

In [51]:
# Fill null values for 'Note Title' in the notes dataset
notes['Note Title'] = notes['Note Title'].fillna('Not available')

# Fill null values for 'Note Content' in the notes dataset
notes['Note Content'] = notes['Note Content'].fillna('Not available')

#**Data Visualization and insight generation**

In [52]:
# KPI cards
total_candidates_contacted = crm.shape[0]
print(f"Total candidates contacted (number of rows in crm dataset): {total_candidates_contacted}")

Total candidates contacted (number of rows in crm dataset): 46469

In [53]:
invoice_counts = enrolled['Invoice'].value_counts()
registered_candidates = invoice_counts.get('Yes', 0)
enrolled_candidates = invoice_counts.sum()
unregistered_candidates = enrolled_candidates - registered_candidates

print("Unregistered candidates:", unregistered_candidates)
print("Registered candidates:", invoice_counts.get('Yes', 0))
print("Enrolled candidates:", invoice_counts.sum())

Unregistered candidates: 190
Registered candidates: 1084
Enrolled candidates: 1274

In [54]:
program_joined_counts = enrolled['Program Joined'].value_counts()

not_joined_candidates = program_joined_counts.get('Not joined', 0)
total_candidates = program_joined_counts.sum()
joined_candidates = total_candidates - not_joined_candidates

print("Candidates not joined in any program:", not_joined_candidates)
print("Joined candidates:", joined_candidates)

Candidates not joined in any program: 239
Joined candidates: 1035

In [56]:
program_joined_with_invoice_count = enrolled[(enrolled['Program Joined'] != 'Not joined') & (enrolled['Invoice'] == 'Yes')].shape[0]
print(f"Candidates who joined a program AND have an invoice (Active candidates): {program_joined_with_invoice_count}")

churned_program_invoice_status = enrolled[enrolled['Program Joined'] == 'Not joined']['Invoice'].value_counts()
churned_candidates = churned_program_invoice_status.get('Yes', 0)

print("Churned candidates (Invoice Yes, Program Not Joined):", churned_candidates)

churned_candidates_count = churned_program_invoice_status.get('Yes', 0)
active_candidates_count = program_joined_with_invoice_count # Updated to use program_joined_with_invoice_count

candidate_status_data = pd.Series({
    'Churned Candidates (Invoice Yes, Program not Joined)': churned_candidates_count,
    'Active Candidates (Joined Program)': active_candidates_count
})

joined_no_invoice = joined_candidates - active_candidates_count
print("Joined candidates without invoice:", joined_no_invoice)

non_active_candidates = churned_program_invoice_status.get('No', 0)
print("Inactive candidates (Invoice No, Program Not Joined):", non_active_candidates)

Candidates who joined a program AND have an invoice (Active candidates): 980
Churned candidates (Invoice Yes, Program Not Joined): 104
Joined candidates without invoice: 55
Inactive candidates (Invoice No, Program Not Joined): 135