<a href="https://colab.research.google.com/github/eldhosekroy/churn_prediction/blob/main/Churn_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # Corrected import for plotting
import seaborn as sns
import os

In [3]:
base_dir = os.getcwd()

input_dir = base_dir

enrolled_file = os.path.join(input_dir, 'Endrolled & registred.xlsx')

enrolled = pd.read_excel(enrolled_file)

enrolled.head(3)

,Contact Id,Contact Owner.id,Contact Owner,First Name,Last Name,Email Opt Out,college Name.id,college Name,Track Interested,Tag,...,Gender,Year of Graduation,Experience,Test,Followup Email,Invoice,Mode of Program Joined,Program Location,Region,Whatsapp Number
0,zcrm_560042000000440092,zcrm_560042000000283001,SalesPerson-2,NaN,AJSAL Mohammed T S,False,NaN,NaN,Python Full stack,NaN,...,Male,NaN,NaN,False,False,Yes,NaN,NaN,NaN,NaN
1,zcrm_560042000000466061,zcrm_560042000000283001,SalesPerson-2,NaN,Abhishek R J,False,NaN,NaN,Datascience,NaN,...,NaN,2022.0,NaN,False,False,NaN,NaN,NaN,NaN,NaN
2,zcrm_560042000000565094,zcrm_560042000000331113,SalesPerson-9,Alan,Thomas,False,NaN,NaN,NaN,NaN,...,Male,2023.0,NaN,False,False,Yes,NaN,NaN,NaN,NaN

In [4]:
enrolled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274 entries, 0 to 1273
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Contact Id              1274 non-null   object
 1   Contact Owner.id        1274 non-null   object
 2   Contact Owner           1274 non-null   object
 3   First Name              152 non-null    object
 4   Last Name               1274 non-null   object
 5   Email Opt Out           1274 non-null   bool
 6   college Name.id         65 non-null     object
 7   college Name            65 non-null     object
 8   Track Interested        556 non-null    object
 9   Tag                     402 non-null    object
 10  Description             68 non-null     object
 11  Created By.id           1274 non-null   object
 12  Modified By.id          1274 non-null   object
 13  Created Time            1274 non-null   datetime64[ns]
 14  Modified Time           1274 non-null   datetime64[ns]
 15  Last Activity Time      1274 non-null   datetime64[ns]
 16  Unsubscribed Mode       0 non-null      float64
 17  Unsubscribed Time       0 non-null      float64
 18  Contact Name            1274 non-null   object
 19  City                    254 non-null    object
 20  Mailing State           9 non-null      object
 21  Mailing Zip             3 non-null      float64
 22  Mailing Country         8 non-null      object
 23  Program Joined.id       1035 non-null   object
 24  Program Joined          1035 non-null   object
 25  Source of lead          1109 non-null   object
 26  Pipeline owner.id       1011 non-null   object
 27  Semester                42 non-null     float64
 28  Batch Assigned to       237 non-null    object
 29  Lead Generated on       848 non-null    datetime64[ns]
 30  Course                  413 non-null    object
 31  Gender                  300 non-null    object
 32  Year of Graduation      319 non-null    float64
 33  Experience              14 non-null     float64
 34  Test                    1274 non-null   bool
 35  Followup Email          1274 non-null   bool
 36  Invoice                 1084 non-null   object
 37  Mode of Program Joined  440 non-null    object
 38  Program Location        438 non-null    object
 39  Region                  18 non-null     object
 40  Whatsapp Number         4 non-null      float64
dtypes: bool(3), datetime64[ns](4), float64(7), object(27)
memory usage: 382.1+ KB

In [5]:
enrolled.describe()

,Created Time,Modified Time,Last Activity Time,Unsubscribed Mode,Unsubscribed Time,Mailing Zip,Semester,Lead Generated on,Year of Graduation,Experience,Whatsapp Number
count,1274,1274,1274,0.0,0.0,3.000000,42.000000,848,319.000000,14.000000,4.000000e+00
mean,2025-03-02 01:55:06.603610624,2025-06-04 11:53:38.827315200,2025-06-15 06:58:25.073783296,NaN,NaN,679012.000000,5.023810,2024-11-02 04:43:35.094339584,2079.304075,0.071429,8.479450e+08
min,2023-12-07 16:29:44,2024-09-25 19:25:20,2024-09-25 19:25:20,NaN,NaN,673005.000000,2.000000,2003-06-10 00:00:00,2006.000000,0.000000,7.012189e+08
25%,2024-09-05 11:19:18,2025-01-22 12:24:57.500000,2025-01-22 14:49:26,NaN,NaN,677503.000000,4.000000,2024-06-23 00:00:00,2022.000000,0.000000,7.818011e+08
50%,2025-03-25 10:36:57.500000,2025-05-19 12:46:35,2025-05-19 12:50:00,NaN,NaN,682001.000000,6.000000,2024-11-04 12:00:00,2024.000000,0.000000,8.580451e+08
75%,2025-09-02 13:42:19.500000,2025-10-15 10:38:05,2025-10-15 10:38:06,NaN,NaN,682015.500000,6.000000,2025-07-01 00:00:00,2024.000000,0.000000,9.241890e+08
max,2026-02-23 11:44:53,2026-02-23 12:05:52,2026-02-24 17:14:04,NaN,NaN,682030.000000,8.000000,2026-02-23 00:00:00,20224.000000,1.000000,9.744707e+08
std,NaN,NaN,NaN,NaN,NaN,5202.234808,1.370207,NaN,1019.109883,0.267261,1.191900e+08

In [6]:
float_columns = enrolled.select_dtypes(include=['float64']).columns

for col in float_columns:
    # Fill NaN values with 0 and then convert to integer
    enrolled[col] = enrolled[col].fillna(0).astype(int)

print("Data types after converting float columns to int:")
enrolled.info()

Data types after converting float columns to int:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1274 entries, 0 to 1273
Data columns (total 41 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Contact Id              1274 non-null   object
 1   Contact Owner.id        1274 non-null   object
 2   Contact Owner           1274 non-null   object
 3   First Name              152 non-null    object
 4   Last Name               1274 non-null   object
 5   Email Opt Out           1274 non-null   bool
 6   college Name.id         65 non-null     object
 7   college Name            65 non-null     object
 8   Track Interested        556 non-null    object
 9   Tag                     402 non-null    object
 10  Description             68 non-null     object
 11  Created By.id           1274 non-null   object
 12  Modified By.id          1274 non-null   object
 13  Created Time            1274 non-null   datetime64[ns]
 14  Modified Time           1274 non-null   datetime64[ns]
 15  Last Activity Time      1274 non-null   datetime64[ns]
 16  Unsubscribed Mode       1274 non-null   int64
 17  Unsubscribed Time       1274 non-null   int64
 18  Contact Name            1274 non-null   object
 19  City                    254 non-null    object
 20  Mailing State           9 non-null      object
 21  Mailing Zip             1274 non-null   int64
 22  Mailing Country         8 non-null      object
 23  Program Joined.id       1035 non-null   object
 24  Program Joined          1035 non-null   object
 25  Source of lead          1109 non-null   object
 26  Pipeline owner.id       1011 non-null   object
 27  Semester                1274 non-null   int64
 28  Batch Assigned to       237 non-null    object
 29  Lead Generated on       848 non-null    datetime64[ns]
 30  Course                  413 non-null    object
 31  Gender                  300 non-null    object
 32  Year of Graduation      1274 non-null   int64
 33  Experience              1274 non-null   int64
 34  Test                    1274 non-null   bool
 35  Followup Email          1274 non-null   bool
 36  Invoice                 1084 non-null   object
 37  Mode of Program Joined  440 non-null    object
 38  Program Location        438 non-null    object
 39  Region                  18 non-null     object
 40  Whatsapp Number         1274 non-null   int64
dtypes: bool(3), datetime64[ns](4), int64(7), object(27)
memory usage: 382.1+ KB

In [7]:
enrolled['Contact Id'].duplicated().sum()

np.int64(0)

In [8]:
enrolled['Contact Id'].isnull().sum()

np.int64(0)

In [9]:
enrolled['Invoice'] = enrolled['Invoice'].fillna('No')
enrolled['Invoice'] = enrolled['Invoice'].replace('yes', 'Yes')

enrolled['Program Joined'] = enrolled['Program Joined'].fillna('Not joined')

nonactive_candidates = enrolled[(enrolled['Invoice'] == 'No') & (enrolled['Program Joined'] == 'Not joined')].shape[0]
nonactive_candidates

135

In [10]:
enrolled = enrolled[~((enrolled['Invoice'] == 'No') & (enrolled['Program Joined'] == 'Not joined'))]

print(f"Shape of enrolled DataFrame after removing non-active candidates: {enrolled.shape}")

Shape of enrolled DataFrame after removing non-active candidates: (1139, 41)

In [11]:
columns_to_drop = [
    'First Name',
    'Last Name',
    'Email Opt Out',
    'college Name.id',
    'college Name',
    'Unsubscribed Mode',
    'Unsubscribed Time',
    'City',
    'Mailing State',
    'Mailing Zip',
    'Mailing Country',
    'Whatsapp Number',
    'Region'
]

enrolled = enrolled.drop(columns=columns_to_drop)

print(f"Shape of enrolled DataFrame after dropping columns: {enrolled.shape}")
display(enrolled.head())

Shape of enrolled DataFrame after dropping columns: (1139, 28)

,Contact Id,Contact Owner.id,Contact Owner,Track Interested,Tag,Description,Created By.id,Modified By.id,Created Time,Modified Time,...,Lead Generated on,Course,Gender,Year of Graduation,Experience,Test,Followup Email,Invoice,Mode of Program Joined,Program Location
0,zcrm_560042000000440092,zcrm_560042000000283001,SalesPerson-2,Python Full stack,NaN,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2023-12-19 11:01:38,2024-09-25 19:25:56,...,2023-12-19,Btech-Non IT,Male,0,0,False,False,Yes,NaN,NaN
1,zcrm_560042000000466061,zcrm_560042000000283001,SalesPerson-2,Datascience,NaN,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2023-12-26 15:20:10,2024-09-25 19:26:18,...,2023-12-26,BCom,NaN,2022,0,False,False,No,NaN,NaN
2,zcrm_560042000000565094,zcrm_560042000000331113,SalesPerson-9,NaN,NaN,NaN,zcrm_560042000000331113,zcrm_560042000000283001,2024-01-22 10:50:27,2024-09-25 19:28:00,...,2024-01-22,BCA,Male,2023,0,False,False,Yes,NaN,NaN
3,zcrm_560042000000583691,zcrm_560042000000331113,SalesPerson-9,NaN,Ayisha,NaN,zcrm_560042000000331113,zcrm_560042000000283001,2024-01-23 15:26:32,2025-05-19 12:49:04,...,2024-01-23,BCA,Male,2023,0,False,False,Yes,NaN,NaN
4,zcrm_560042000000604837,zcrm_560042000000283001,SalesPerson-2,NaN,Enrolled,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2024-01-28 22:15:36,2024-10-02 12:37:59,...,2024-01-18,MSc computer science (data analytics),NaN,2024,0,False,True,Yes,NaN,NaN

In [12]:
import re

# First, standardize the 'Program Joined' column as requested.
def standardize_program_joined_text(program_string):
    if pd.isna(program_string) or program_string == 'Churned':
        return program_string

    program_string = str(program_string)

    # 1. Standardize month names (full to short form, and ensure proper case)
    month_mapping = {
        'January': 'Jan', 'February': 'Feb', 'March': 'Mar', 'April': 'Apr',
        'May': 'May', 'June': 'Jun', 'July': 'Jul', 'August': 'Aug',
        'September': 'Sep', 'October': 'Oct', 'November': 'Nov', 'December': 'Dec'
    }
    for full, short in month_mapping.items():
        program_string = re.sub(r'\b' + full + r'\b', short, program_string, flags=re.IGNORECASE)

    # Ensure month abbreviations are capitalized (e.g., "jan" -> "Jan")
    program_string = re.sub(r'\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\b', lambda x: x.group(0).capitalize(), program_string, flags=0)

    # 2. Standardize common program keywords/abbreviations (case-insensitive search, consistent replacement)
    program_string = re.sub(r'\bprogramme\b', 'Program', program_string, flags=re.IGNORECASE)
    # Fix for 'Enrolleeee' issue: replace 'enroll' or 'enrollee' with 'Enrollee' (word boundary for accurate replacement)
    program_string = re.sub(r'\b(enroll|enrollee)\b', 'Enrollee', program_string, flags=re.IGNORECASE)

    # Specific course abbreviations - these should be uppercase
    program_string = re.sub(r'\bmern stack\b', 'MERN', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bmern\b', 'MERN', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata analytics\b', 'DA', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata analytic\b', 'DA', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata science\b', 'DS', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bdata sci\b', 'DS', program_string, flags=re.IGNORECASE)
    program_string = re.sub(r'\bfull stack\b', 'FS', program_string, flags=re.IGNORECASE)

    # Standardize 'One Month Program' variations
    program_string = re.sub(r'\b(One Month Programme|One Month Program)\b', 'One Month Program', program_string, flags=re.IGNORECASE)

    # Clean up extra spaces
    program_string = ' '.join(program_string.split())

    # Final capitalization for desired format (e.g., "DA May 2024"), then fix abbreviations
    program_string = program_string.title()
    program_string = program_string.replace('Da', 'DA').replace('Ds', 'DS').replace('Mern', 'MERN').replace('Fs', 'FS')
    # Ensure Enrollee keeps its capitalization
    program_string = program_string.replace('Enrollee', 'Enrollee')
    program_string = program_string.replace('One Month Program', 'One Month Program') # Keep as is after title()

    return program_string

# Apply this initial standardization to the 'Program Joined' column
enrolled['Program Joined Standardized'] = enrolled['Program Joined'].apply(standardize_program_joined_text)


# Now define and apply the function to extract year and a *very* clean course name
def extract_year_and_course(program_string):
    if pd.isna(program_string) or program_string == 'Churned':
        return None, 'Churned'

    program_string = str(program_string)

    # Extract year
    year_match = re.search(r'\b(202[0-9]|203[0-9]|204[0-9])\b', program_string)
    year = int(year_match.group(1)) if year_match else None

    cleaned_course_name = program_string
    # Remove year and month abbreviations
    cleaned_course_name = re.sub(r'\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b', '', cleaned_course_name, flags=0)
    cleaned_course_name = re.sub(r'\b(202[0-9]|203[0-9]|204[0-9])\b', '', cleaned_course_name)

    # Aggressively remove common extra words, standalone numbers, and specific unwanted patterns
    extra_words_to_remove = [
        'Program', 'Enrollee', 'One Month', 'Advanced', 'Training', 'Bootcamp', 'Course', 'Classes',
        'Online', 'Offline', 'Batch', 'Session', 'Beginner', 'Intermediate', 'Expert', 'Module'
    ]
    # Remove these words case-insensitively
    cleaned_course_name = re.sub(r'\b(' + '|'.join(extra_words_to_remove) + r')\b', '', cleaned_course_name, flags=re.IGNORECASE)

    # Remove any standalone numbers (e.g., 'DA 25' -> 'DA ') or numbers attached to words (e.g., 'DA25' -> 'DA')
    cleaned_course_name = re.sub(r'\s*\d+\s*', ' ', cleaned_course_name) # Remove standalone numbers
    cleaned_course_name = re.sub(r'\b([A-Z]+)(\d+)\b', r'\1', cleaned_course_name) # Remove trailing numbers like 'DA25'

    cleaned_course_name = re.sub(r' & ', '&', cleaned_course_name) # Standardize ampersand
    cleaned_course_name = cleaned_course_name.strip()
    cleaned_course_name = ' '.join(cleaned_course_name.split()) # Remove multiple spaces
    cleaned_course_name = cleaned_course_name.upper() # Convert to uppercase for final standardization

    final_course_name = 'UNSPECIFIED'

    # Define primary course names to recognize as prefixes, sorted by length (descending)
    primary_course_names = [
        'ROUNDED DS&GENAI PROFESSIONAL', 'GEN AI&PROMPT ENG', 'WEB DEV', 'MERN', 'FULL STACK',
        'DATA ANALYTICS', 'DATA SCIENCE', 'DS&ALGORITHMS', 'PYTHON', 'MLOPS', 'AI', 'BA', 'DM', 'ML',
        'DA', 'DS', 'FS', 'PEP', 'PY'
    ]
    primary_course_names.sort(key=len, reverse=True) # Ensure longer names are checked first

    found_primary = False
    for pc_name in primary_course_names:
        # Check if the cleaned course name starts with a primary course name, or is exactly it
        if cleaned_course_name.startswith(pc_name) or cleaned_course_name == pc_name:
            final_course_name = pc_name
            found_primary = True
            break

    # If no primary course name was found by prefix, but the cleaned_course_name is not empty, use it as is or apply specific mappings
    if not found_primary and cleaned_course_name != '':
        course_name_exact_mapping = {
            'DATA ANALYTICS': 'DA',
            'DATA SCIENCE': 'DS',
            'FULL STACK': 'FS',
            'MERN STACK': 'MERN',
            'ADVANCED': 'ADVANCED',
            'EE': 'ENROLLEE',
            'DA ENROLLEE': 'DA'
        }
        final_course_name = course_name_exact_mapping.get(cleaned_course_name, cleaned_course_name)

    # Ensure 'Churned' overrides any other logic if the original program_string was 'Churned'
    if program_string == 'Churned':
        final_course_name = 'Churned'
    elif final_course_name == '': # If it became empty after all processing, default to UNSPECIFIED
        final_course_name = 'UNSPECIFIED'

    return year, final_course_name

# Apply the year and course extraction on the newly standardized 'Program Joined Standardized' column
enrolled[['Program_Year', 'Course_Name']] = enrolled['Program Joined Standardized'].apply(lambda x: pd.Series(extract_year_and_course(x)))

# Convert 'Program_Year' to nullable integer type to remove decimal part while retaining NaN values
enrolled['Program_Year'] = enrolled['Program_Year'].astype(pd.Int64Dtype())

In [13]:
enrolled.head()

,Contact Id,Contact Owner.id,Contact Owner,Track Interested,Tag,Description,Created By.id,Modified By.id,Created Time,Modified Time,...,Year of Graduation,Experience,Test,Followup Email,Invoice,Mode of Program Joined,Program Location,Program Joined Standardized,Program_Year,Course_Name
0,zcrm_560042000000440092,zcrm_560042000000283001,SalesPerson-2,Python Full stack,NaN,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2023-12-19 11:01:38,2024-09-25 19:25:56,...,0,0,False,False,Yes,NaN,NaN,Not Joined,<NA>,NOT JOINED
1,zcrm_560042000000466061,zcrm_560042000000283001,SalesPerson-2,Datascience,NaN,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2023-12-26 15:20:10,2024-09-25 19:26:18,...,2022,0,False,False,No,NaN,NaN,DA May 2024,2024,DA
2,zcrm_560042000000565094,zcrm_560042000000331113,SalesPerson-9,NaN,NaN,NaN,zcrm_560042000000331113,zcrm_560042000000283001,2024-01-22 10:50:27,2024-09-25 19:28:00,...,2023,0,False,False,Yes,NaN,NaN,Not Joined,<NA>,NOT JOINED
3,zcrm_560042000000583691,zcrm_560042000000331113,SalesPerson-9,NaN,Ayisha,NaN,zcrm_560042000000331113,zcrm_560042000000283001,2024-01-23 15:26:32,2025-05-19 12:49:04,...,2023,0,False,False,Yes,NaN,NaN,Not Joined,<NA>,NOT JOINED
4,zcrm_560042000000604837,zcrm_560042000000283001,SalesPerson-2,NaN,Enrolled,NaN,zcrm_560042000000283001,zcrm_560042000000283001,2024-01-28 22:15:36,2024-10-02 12:37:59,...,2024,0,False,True,Yes,NaN,NaN,DA Enrollee Sep 2024,2024,DA